# Generated by Django 4.0.4 on 2022-05-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_record_remove_habit_habit_habit_name_habit_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('date', 'habit'), name='daily'),
        ),
    ]
