# Generated by Django 4.0.4 on 2022-05-18 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_habit_created_at_record_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='record',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(),
        ),
    ]
