# Generated by Django 4.0.4 on 2022-05-19 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_record_daily_alter_record_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='record',
            name='daily_record',
        ),
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('date', 'habit', 'user'), name='daily_record'),
        ),
    ]
